# A custom image for spark is being used to install any dependencies on it a single time.
# This means that `spark_custom:0.1` has to be built before using it.
# A simple `docker build --network host -t spark_custom:0.1 ./docker/spark_custom` should suffice.
services:
  spark:
    # image: jupyter/pyspark-notebook
    image: spark_custom:0.1
    container_name: spark_container
    ports:
      - "8888:8888"
    volumes:
      - ./v_spark:/home/jovyan
    networks:
      - shared_network
    environment:
      - GRANT_SUDO=yes
      - AWS_ACCESS_KEY_ID=test_key_id
      - AWS_SECRET_ACCESS_KEY=test_access_key

  s3:
    image: localstack/localstack:s3-latest
    container_name: s3_container
    environment:
      - AWS_ACCESS_KEY_ID=test_key_id
      - AWS_SECRET_ACCESS_KEY=test_access_key
    expose:
      - "4566"
    ports:
      - "127.0.0.1:4566:4566"
    volumes:
      # We might need to change this S3 path here to something else
      # - ./v_s3:/tmp/localstack_random
      - ./v_s3:/var/lib/localstack
    networks:
      - shared_network

  neo4j:
    image: neo4j:5.17.0-community-bullseye
    container_name: neo4j_container
    environment:
      - NEO4J_AUTH=none
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=\[\"graph-data-science\"\]
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./v_neo4j/import:/var/lib/neo4j/import
      - ./v_neo4j/logs:/var/lib/neo4j/logs
      - ./v_neo4j/conf:/var/lib/neo4j/conf
    networks:
      - shared_network


# volumes:
#   v_s3:
#     name: v_s3
  # v_spark:
    # name: v_spark


networks:
  shared_network:
    driver: bridge
# docker stop SPARK ; docker rm SPARK ; docker run --name SPARK -p 8888:8888 -v ~/bdma/upc/big_data_management/project/Gecko/p2:/home/jovyan jupyter/pyspark-notebook

#     -p 7474:7474 \
#     -p 7687:7687 \
#     --env=NEO4J_AUTH=none \
#     -v ${BASE_DIR}/SDM_Lab1/neo4j/import:/var/lib/neo4j/import \
#     -v ${BASE_DIR}/SDM_Lab1/neo4j/logs:/var/lib/neo4j/logs \
#     -v ${BASE_DIR}/SDM_Lab1/neo4j/conf:/var/lib/neo4j/conf \
#     -e NEO4J_apoc_export_file_enabled=true \
#     -e NEO4J_apoc_import_file_enabled=true \
#     -e NEO4J_apoc_import_file_use__neo4j__config=true \
#     -e NEO4J_PLUGINS=\[\"graph-data-science\"\] \
#     neo4j:5.17.0-community-bullseye
